### ISSUE TITLE
Document need for wget

### ISSUE THREAD

**Issue by duane** [termoshtt/rust-fftw3#30]
Otherwise, calling `cargo build` will fail with an error that took me a few minutes to chase down:

```
error: failed to run custom build command for `fftw-src v0.2.1`
process didn't exit successfully: `/Users/duane/Projects/audio/spectrogram/target/debug/build/fftw-src-1e03addce5c52064/build-script-build` (exit code: 101)
--- stdout
Running: "wget" "http://www.fftw.org/fftw-3.3.6-pl1.tar.gz"

--- stderr
thread 'main' panicked at 'failed to execute `"wget" "http://www.fftw.org/fftw-3.3.6-pl1.tar.gz"`: No such file or directory (os error 2)', /Users/duane/.cargo/registry/src/github.com-1ecc6299db9ec823/fftw-src-0.2.1/build.rs:61
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Note at first I thought the target file was missing, not wget.

Alternatively, you could just use curl on darwin.

**Comment by termoshtt** [comment]
I have same problem on building document on docs.rs, and I'm rewriting build.rs to use curl. thanks.

**Comment by termoshtt** [comment]
I have added the requirements in README, and rewrite `fftw-sys/build.rs` to use `curl` instead of `wget`.
