### ISSUE TITLE
thread 'main' panicked at 'Failed to check md5 sum

### ISSUE THREAD

**Issue by jim323** [termoshtt/rust-fftw3#53]
I'm new to Rust , so please over look my ignorance of some its functions. I have iMac osx 10.13.6
My issue is the following:error:
 failed to run custom build command for `fftw-src v0.2.2 (file:///Users/jim/Downloads/rust-fftw3-master-2/fftw-src)`
process didn't exit successfully: `/Users/jim/Downloads/rust-fftw3-master-2/target/debug/build/fftw-src-a110d0ce96cf96b8/build-script-build` (exit code: 101)
--- stderr
thread 'main' panicked at 'Failed to check md5 sum: Os { code: 2, kind: NotFound, message: "No such file or directory" }', libcore/result.rs:945:5

Any help will be greatly appreciated.

**Comment by termoshtt** [comment]
It seems to be caused by the lack of `md5sum` command, which macOS does not contain by default. Please install md5sum by brew or other way.

I did not test this crate on macOS. I will switch to use pure rust crates for calc check-sum. Thanks report.

**Comment by jim323** [comment]
Thank you very much . I appreciate the suggestion,will try it.

**Comment by termoshtt** [comment]
I've release fftw-src-0.2.3, which does not require external `md5sum` command. If you have not try above yet, please `cargo update`.

**Comment by jim323** [comment]
Thanks, that worked. On  first try this appears to be the fastest rust fft that I have found, as would be expected from FFTW.
As far as I'm concerned this closes my issue.
