### ISSUE TITLE
num-complex v0.2.0 support seems to be broken

### ISSUE THREAD

**Issue by shradej1** [termoshtt/rust-fftw3#58]
It looks like the fftw-sys dependency is stuck on v0.2.4 which uses num-complex v0.1.43.

Creating a minimal project with the following dependencies

    [dependencies]
    fftw = "0.5.0"
    num-complex = "0.2.0"

causes cargo to pull down both num-complex v0.2.0 and num-complex v0.1.43.  Cargo reports that it's using v0.3.0 of fftw-sys, but the actual Cargo.toml in the registry (~/.cargo/registry/src/github.com-1ecc6299db9ec823/fftw-sys-0.3.0) shows version 0.2.4 with the old num-complex dependency.

    use num_complex::Complex;
    use fftw::array::AlignedVec;

    fn main() {
        let v: AlignedVec<Complex<f64>> = AlignedVec::new(1);
    }

errors with "the trait `fftw::array::AlignedAllocable` is not implemented for `num_complex::Complex<f64>`"

Changing the num-complex dependency version to 0.1.43 allows the above to compile.

**Comment by termoshtt** [comment]
Thanks report. I released fftw-sys-0.4.0 for num-complex 0.2, and fftw-0.5.1 for fftw-sys 0.4.0
